### PR TITLE
update to openresty 1.7.10.1

### PR DESCRIPTION
**Pull request by kikito**
Basically an update to the latest version. I don't know if I need to change anything else (it doesn't seem it is needed)

### CODE REVIEW

**Comment by fermaem** [comment]
@mikz Any chance you may consider merging this? Or even better maybe upgrade to the latest openresty version?

Thanks in advance for your feedback.

**Comment by fermaem** [comment]
:heart_eyes:

**Comment by fermaem** [comment]
@mikz When do you think this new version could be published on dockerhub?

**Comment by mikz** [comment]
@fermaem it is automatically built on our quay.io - https://quay.io/repository/3scale/openresty?tab=tags

**Pull request merged**
